---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-common
  labels:
    name: vcu-common

---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-common
  labels:
    name: du-common

---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common"
  namespace: "ztp-common"
  annotations:
    force: "force-again"
spec:
  bindingRules:
    common: "true"
    group-vcu-4.12: ""
  sourceFiles:
    # Create operators policies that will be installed in all clusters
    # SRIOV
    - fileName: SriovSubscription.yaml
      policyName: "sriov-sub-policy"
      spec:
        channel: "4.11"
        installPlanApproval: Automatic
    - fileName: SriovSubscriptionNS.yaml
      policyName: "sriov-sub-policy"
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "sriov-sub-policy"
    # PTP
    - fileName: PtpSubscription.yaml
      policyName: "ptp-sub-policy"
      spec:
        channel: "stable"
        installPlanApproval: Automatic
    - fileName: PtpSubscriptionNS.yaml
      policyName: "ptp-sub-policy"
    - fileName: PtpSubscriptionOperGroup.yaml
      policyName: "ptp-sub-policy"
    # PAO
    - fileName: NtoSubscription.yaml
      policyName: "nto-sub-policy"
      spec:
        source: redhat-operators
        channel: "4.11"
        installPlanApproval: Automatic
    - fileName: NtoSubscriptionNS.yaml
      policyName: "nto-sub-policy"
    - fileName: NtoSubscriptionOperGroup.yaml
      policyName: "nto-sub-policy"
    # CLO
#    - fileName: ClusterLogOperGroup.yaml
#      policyName: "log-sub-policy"
#    - fileName: ClusterLogSubscription.yaml
#      policyName: "log-sub-policy"
    # LSO
    - fileName: StorageNS.yaml
      policyName: "storage-sub-policy"
    - fileName: StorageOperGroup.yaml
      policyName: "storage-sub-policy"
    - fileName: StorageSubscription.yaml
      policyName: "storage-sub-policy"
      spec:
        channel: "4.11"
        installPlanApproval: Automatic
    # Reduce Monitoring Operator Footprint
    - fileName: ReduceMonitoringFootprint.yaml
      policyName: "mon-offload-policy"
    - fileName: extra-manifest/06-kdump-master.yaml
      policyName: "kdump-policy"
    # These CRs are in support of installation from a disconnected registry
#    - fileName: ClusterLogCatSource.yaml
#      policyName: "log-sub-policy"
#      spec:
#        image: registry.example.com:5000/olm/far-edge-clo:latest
#    - fileName: PtpCatSource.yaml
#      policyName: "ptp-sub-policy"
#      spec:
#        image: registry.example.com:5000/olm/far-edge-ptp:latest
#    - fileName: StorageCatSource.yaml
#      policyName: "storage-sub-policy"
#      spec:
#        image: registry.example.com:5000/olm/far-edge-lso:latest
#    - fileName: SriovCatSource.yaml
#      policyName: "sriov-sub-policy"
#      spec:
#        image: registry.example.com:5000/olm/far-edge-sriov:latest
#    - fileName: DisconnectedICSP.yaml
#      policyName: "disc-icsp-policy"
#      spec:
#        repositoryDigestMirrors:
#        - mirrors:
#          - registry.redhat.com:5000
#          source: registry.redhat.io
#    - fileName: OperatorHub.yaml
#      policyName: "oper-hub-policy

