---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: cloudransno-site1
stringData:
  .dockerconfigjson: '<pull-secret>'
  type: kubernetes.io/dockerconfigjson

