---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudranvcu
---

apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: vcu
stringData:
  .dockerconfigjson: '<pull-secret>'
  type: kubernetes.io/dockerconfigjson

